export const BASE = "/aircentralofthecarolinas";

export const COMPANY = {
  name: "Air Central Of The Carolinas",
  shortName: "Air Central",
  tagline: "Trusted Heating & Cooling for Indian Trail and the Charlotte Area",
  phone: "(704) 288-4822",
  phoneHref: "tel:+17042884822",
  email: "info@aircentralofthecarolinas.com",
  address: "Indian Trail, NC 28079",
  city: "Indian Trail",
  state: "NC",
  zip: "28079",
  hours: {
    weekdays: "Mon–Fri: 7:00 AM – 6:00 PM",
    saturday: "Sat: 8:00 AM – 4:00 PM",
    sunday: "Sun: Emergency Service Only",
  },
  social: {
    facebook: "#",
    instagram: "#",
    google: "#",
  },
};

export const navLinks = [
  { label: "Home", href: BASE },
  { label: "About", href: `${BASE}/about` },
  {
    label: "Services",
    href: `${BASE}/services`,
    children: [
      { label: "AC Repair", href: `${BASE}/services/ac-repair` },
      { label: "AC Installation", href: `${BASE}/services/ac-installation` },
      { label: "Heating Repair", href: `${BASE}/services/heating-repair` },
      { label: "Heating Installation", href: `${BASE}/services/heating-installation` },
      { label: "Heat Pumps", href: `${BASE}/services/heat-pumps` },
      { label: "Preventive Maintenance", href: `${BASE}/services/preventive-maintenance` },
      { label: "Indoor Air Quality", href: `${BASE}/services/indoor-air-quality` },
      { label: "Home Energy Audits", href: `${BASE}/services/home-energy-audits` },
      { label: "Commercial HVAC", href: `${BASE}/services/commercial-hvac` },
    ],
  },
  { label: "Financing", href: `${BASE}/financing` },
  { label: "Specials", href: `${BASE}/specials` },
  { label: "Service Areas", href: `${BASE}/service-areas` },
  { label: "Contact", href: `${BASE}/contact` },
];

export const services = [
  {
    slug: "ac-repair",
    title: "AC Repair",
    shortTitle: "AC Repair",
    icon: "Thermometer",
    category: "Cooling",
    description: "Fast, accurate diagnosis and repair for all central air conditioning systems. We fix it right the first time.",
    longDescription: "When your air conditioner stops working, you need a team that can diagnose the problem quickly and fix it properly — not guess and come back. Our technicians are trained on all major AC brands and system types, from older units to the newest variable-speed systems. We carry common parts on every truck so most repairs are completed same-day.",
    keywords: ["AC repair Indian Trail NC", "air conditioner repair Charlotte", "central AC not cooling", "HVAC repair near me"],
    signs: [
      "AC isn't cooling your home as well as it used to",
      "Unusual noises — grinding, squealing, or banging",
      "Ice forming on the unit or refrigerant lines",
      "Frequent cycling on and off",
      "Higher-than-normal energy bills",
      "Water leaking around the indoor unit",
    ],
    included: [
      "Full system diagnostic and pressure check",
      "Inspect all electrical components and controls",
      "Check refrigerant levels and test for leaks",
      "Inspect coils, capacitors, contactors, and fan motors",
      "Provide written estimate before any repair",
      "Test system performance after repair",
    ],
    faq: [
      {
        q: "How long does an AC repair take?",
        a: "Most repairs are completed in 1–3 hours. More complex issues like refrigerant recharges or coil replacements may take longer. We'll give you a clear time estimate before we start.",
      },
      {
        q: "Is it worth repairing an older AC unit?",
        a: "It depends on the age, condition, and cost of the repair. We'll give you an honest recommendation — if replacement makes more sense financially, we'll tell you.",
      },
      {
        q: "Do you repair all AC brands?",
        a: "Yes. We service all major brands including Carrier, Lennox, Trane, Goodman, Rheem, York, and more.",
      },
    ],
    relatedServices: ["ac-installation", "preventive-maintenance", "indoor-air-quality"],
    metaTitle: "AC Repair in Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Fast, reliable AC repair in Indian Trail, NC and the Charlotte area. Air Central Of The Carolinas diagnoses and fixes all central air conditioning issues. Call (704) 288-4822.",
  },
  {
    slug: "ac-installation",
    title: "AC Installation",
    shortTitle: "AC Install",
    icon: "Wind",
    category: "Cooling",
    description: "Properly sized, professionally installed central air conditioning systems for long-term comfort and efficiency.",
    longDescription: "A new air conditioning system is a significant investment, and proper sizing and installation determine how well it performs for the next 15–20 years. We perform load calculations to ensure the right system for your home's square footage, insulation, and layout — not just a guess based on what the last system was. We work with top-tier brands and back every installation with a workmanship warranty.",
    keywords: ["AC installation Indian Trail NC", "new central air conditioner Charlotte", "AC replacement near me", "HVAC installation Charlotte area"],
    signs: [
      "Your current system is 12–15+ years old",
      "Repair costs are approaching 50% of replacement cost",
      "Your home has uneven temperatures room to room",
      "Energy bills keep climbing despite regular maintenance",
      "Your system uses R-22 refrigerant (no longer manufactured)",
      "You're adding new square footage or an addition",
    ],
    included: [
      "Manual J load calculation for proper sizing",
      "Full removal and disposal of old equipment",
      "New refrigerant line set installation or flush",
      "Thermostat installation and programming",
      "Electrical disconnect and safety inspection",
      "System startup, test, and homeowner walkthrough",
    ],
    faq: [
      {
        q: "How long does AC installation take?",
        a: "A standard central AC replacement typically takes 4–8 hours. New installations requiring ductwork may take longer.",
      },
      {
        q: "What brands do you install?",
        a: "We install Carrier, Lennox, Trane, Goodman, Rheem, and other top manufacturers. We'll recommend the right brand for your budget and home.",
      },
      {
        q: "Do you offer financing for new AC systems?",
        a: "Yes. We offer flexible financing options to help make a new system affordable. Ask about current promotions.",
      },
    ],
    relatedServices: ["ac-repair", "heat-pumps", "preventive-maintenance"],
    metaTitle: "AC Installation in Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Professional AC installation and replacement in Indian Trail, NC and Charlotte metro. Properly sized systems, expert installation, financing available. Call (704) 288-4822.",
  },
  {
    slug: "heating-repair",
    title: "Heating Repair",
    shortTitle: "Heating Repair",
    icon: "Flame",
    category: "Heating",
    description: "Reliable furnace and heat pump repair when you need it most — fast response, honest diagnosis, quality workmanship.",
    longDescription: "A heating system failure on a cold night is an emergency. Our technicians respond quickly to diagnose and repair gas furnaces, electric furnaces, heat pumps, and all forced-air heating systems. We don't just replace parts — we identify the root cause so the same issue doesn't recur.",
    keywords: ["heating repair Indian Trail NC", "furnace repair Charlotte", "heat pump repair Charlotte area", "emergency heating repair NC"],
    signs: [
      "System blows cold air when heat is called for",
      "Furnace cycles on but shuts off quickly",
      "Unusual smells — burning, sulfur, or musty odors",
      "Pilot light issues or ignition failures",
      "Heating costs have increased significantly",
      "Some rooms heat well while others stay cold",
    ],
    included: [
      "Full diagnostic of heating system and controls",
      "Inspect heat exchanger for cracks (critical safety check)",
      "Test ignition system, flame sensor, and limit switches",
      "Check blower motor, belts, and bearings",
      "Inspect flue and venting for safety",
      "Written repair estimate before any work begins",
    ],
    faq: [
      {
        q: "Is a cracked heat exchanger dangerous?",
        a: "Yes. A cracked heat exchanger can allow carbon monoxide to enter your living space. If we find this issue, we'll explain your options clearly and prioritize your safety.",
      },
      {
        q: "Do you repair heat pumps as well as furnaces?",
        a: "Yes. We repair all heating system types including gas furnaces, electric furnaces, and heat pumps.",
      },
      {
        q: "Do you offer emergency heating repair?",
        a: "Yes. We provide emergency service for heating failures — call us any time.",
      },
    ],
    relatedServices: ["heating-installation", "heat-pumps", "preventive-maintenance"],
    metaTitle: "Heating Repair in Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Reliable heating repair in Indian Trail and Charlotte area. Furnace repair, heat pump service, emergency response. Air Central Of The Carolinas. Call (704) 288-4822.",
  },
  {
    slug: "heating-installation",
    title: "Heating Installation",
    shortTitle: "Heating Install",
    icon: "Heater",
    category: "Heating",
    description: "Expert installation of gas furnaces, electric heating systems, and complete HVAC replacements — done right for lasting comfort.",
    longDescription: "When it's time to replace an aging furnace or heating system, you want it done right. Our team helps you choose the right system for your home's layout, fuel type, and efficiency goals — then installs it with the attention to detail that ensures it operates safely and effectively for years to come.",
    keywords: ["furnace installation Indian Trail NC", "new heating system Charlotte", "furnace replacement Charlotte area", "HVAC installation NC"],
    signs: [
      "Your furnace is over 15–20 years old",
      "Repair costs are becoming frequent and expensive",
      "Your energy bills are significantly higher than average",
      "The system can't maintain comfortable temperatures",
      "Your home has persistent hot/cold spots",
      "You're building a new home or addition",
    ],
    included: [
      "Load calculation to ensure proper sizing",
      "Old equipment removal and disposal",
      "New flue venting installation or inspection",
      "Gas line inspection and connection",
      "Thermostat installation and setup",
      "Full startup test and homeowner walkthrough",
    ],
    faq: [
      {
        q: "What's the most efficient heating option for a Carolina home?",
        a: "Heat pumps are often the most efficient choice for our mild climate. For colder snaps, a dual-fuel system (heat pump + gas backup) offers the best of both worlds. We'll help you evaluate your options.",
      },
      {
        q: "How long does furnace installation take?",
        a: "Most replacements take a full day. New installations with additional work may take 1–2 days.",
      },
    ],
    relatedServices: ["heating-repair", "heat-pumps", "preventive-maintenance"],
    metaTitle: "Heating Installation in Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Professional furnace and heating system installation in Indian Trail, NC and the Charlotte metro area. Air Central Of The Carolinas. Call (704) 288-4822.",
  },
  {
    slug: "heat-pumps",
    title: "Heat Pumps",
    shortTitle: "Heat Pumps",
    icon: "ArrowUpDown",
    category: "Heating & Cooling",
    description: "Heat pump installation, repair, and maintenance — the efficient all-in-one solution for Carolina climates.",
    longDescription: "Heat pumps are the smart choice for most Carolina homeowners — they provide both heating and cooling efficiently, and modern systems work well even in below-freezing temperatures. Whether you're replacing an aging system, upgrading to a mini-split, or investing in a high-efficiency variable-speed heat pump, we'll help you make the right decision.",
    keywords: ["heat pump installation Indian Trail NC", "heat pump repair Charlotte", "mini split installation NC", "heat pump service Charlotte area"],
    signs: [
      "Your current heat pump is 10–15+ years old",
      "The system struggles to heat during cold snaps",
      "You want to reduce your energy bills",
      "You're adding a new room without existing ductwork",
      "You want to replace a gas furnace with an electric option",
      "Your current system runs constantly but can't keep up",
    ],
    included: [
      "Full site evaluation and system recommendations",
      "Sizing calculations and equipment selection guidance",
      "Professional installation with refrigerant handling certification",
      "Electrical work and disconnect installation",
      "Thermostat or smart control setup",
      "System commissioning and performance test",
    ],
    faq: [
      {
        q: "Do heat pumps work in North Carolina winters?",
        a: "Yes. Modern heat pumps work efficiently down to temperatures well below freezing. For extra-cold snaps, we can configure a supplemental heat source to ensure comfort.",
      },
      {
        q: "What's the difference between a heat pump and a regular AC?",
        a: "A heat pump does everything a standard AC does, plus provides heating in winter by reversing the refrigerant cycle. It replaces both your AC and furnace in one unit.",
      },
      {
        q: "Do you install mini-split heat pumps?",
        a: "Yes. We install single-zone and multi-zone ductless mini-split systems for additions, garages, sunrooms, and homes without existing ductwork.",
      },
    ],
    relatedServices: ["ac-installation", "heating-installation", "preventive-maintenance"],
    metaTitle: "Heat Pump Installation & Repair | Indian Trail, NC | Air Central",
    metaDescription: "Heat pump installation, repair, and maintenance in Indian Trail and Charlotte area. Mini-splits, whole-home heat pumps, and dual-fuel systems. Call (704) 288-4822.",
  },
  {
    slug: "preventive-maintenance",
    title: "Preventive Maintenance",
    shortTitle: "Maintenance",
    icon: "ClipboardCheck",
    category: "Maintenance",
    description: "Scheduled HVAC tune-ups that keep your system running clean, efficient, and reliably through every season.",
    longDescription: "The most reliable HVAC systems aren't the most expensive ones — they're the ones that get maintained properly. Our maintenance visits are thorough, not rushed. We inspect, clean, test, and document your system's condition so you have a clear picture of how it's performing and what to expect in coming seasons.",
    keywords: ["HVAC maintenance Indian Trail NC", "AC tune-up Charlotte", "furnace tune-up Charlotte area", "HVAC maintenance plan NC"],
    signs: [
      "It's been more than 12 months since your last service",
      "You've noticed reduced airflow or uneven temperatures",
      "Energy bills are gradually increasing",
      "You want to protect your system warranty",
      "You're heading into cooling or heating season",
      "You want to extend the life of your equipment",
    ],
    included: [
      "Clean evaporator and condenser coils",
      "Inspect and lubricate all moving parts",
      "Test refrigerant levels and check for leaks",
      "Inspect heat exchanger (heating systems)",
      "Clean and test ignition and safety controls",
      "Inspect ductwork connections and filter",
      "Measure airflow and temperature differentials",
      "Provide written condition report",
    ],
    faq: [
      {
        q: "How often should I have my HVAC system serviced?",
        a: "Twice per year — once in spring for your cooling system and once in fall for your heating system. Annual at minimum.",
      },
      {
        q: "Do you offer maintenance agreements?",
        a: "Yes. Our maintenance plans include scheduled visits, priority service, and discounts on repairs. Ask about current plan pricing.",
      },
      {
        q: "Will maintenance help my system last longer?",
        a: "Absolutely. Regular maintenance is the single best thing you can do to extend system life and avoid unexpected breakdowns.",
      },
    ],
    relatedServices: ["ac-repair", "heating-repair", "indoor-air-quality"],
    metaTitle: "HVAC Maintenance Plans | Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Scheduled HVAC maintenance and tune-up service in Indian Trail, NC and Charlotte area. Protect your system investment. Call Air Central at (704) 288-4822.",
  },
  {
    slug: "indoor-air-quality",
    title: "Indoor Air Quality",
    shortTitle: "Air Quality",
    icon: "Leaf",
    category: "Air Quality",
    description: "Cleaner, healthier air in your home through filtration upgrades, UV purification, humidity control, and more.",
    longDescription: "Most people spend the majority of their time indoors — and indoor air can actually be 2–5 times more polluted than outdoor air. We help homeowners address air quality problems with solutions that actually work: high-efficiency filtration, UV air purifiers, whole-home dehumidifiers, and ventilation improvements. We'll assess your home and recommend what makes sense for your situation.",
    keywords: ["indoor air quality Indian Trail NC", "HVAC air purifier Charlotte", "whole home humidifier NC", "air filtration system Charlotte area"],
    signs: [
      "Family members experience frequent allergy or asthma symptoms",
      "Musty or stale odors in the home",
      "Excessive dust accumulation despite regular cleaning",
      "Humidity issues — too dry in winter, too humid in summer",
      "Recent renovation or new construction off-gassing",
      "Concerns about mold, bacteria, or VOCs",
    ],
    included: [
      "Indoor air quality assessment",
      "Filtration system upgrade options and recommendations",
      "UV air purifier installation",
      "Whole-home dehumidifier or humidifier installation",
      "Ventilation improvement evaluation",
      "Filter replacement guidance and schedule",
    ],
    faq: [
      {
        q: "What's the most effective indoor air quality upgrade?",
        a: "It depends on your specific concern. For allergens and dust, a high-MERV filter or air cleaner is most effective. For mold and bacteria, UV purification is excellent. We'll help you prioritize.",
      },
      {
        q: "Can my HVAC system help with humidity control?",
        a: "Yes. Whole-home dehumidifiers and humidifiers connect to your existing HVAC system and maintain balanced humidity year-round — far more effective than portable units.",
      },
    ],
    relatedServices: ["preventive-maintenance", "home-energy-audits", "ac-installation"],
    metaTitle: "Indoor Air Quality Services | Indian Trail, NC | Air Central",
    metaDescription: "Improve your home's air quality with filtration upgrades, UV purifiers, and humidity control in Indian Trail, NC and the Charlotte area. Call (704) 288-4822.",
  },
  {
    slug: "home-energy-audits",
    title: "Home Energy Audits",
    shortTitle: "Energy Audits",
    icon: "BarChart2",
    category: "Efficiency",
    description: "Identify where your home is wasting energy and what to do about it — backed by real data, not guesswork.",
    longDescription: "Rising energy bills aren't always a sign of equipment failure — often the problem is how your home performs as a system. Our energy audit service evaluates your HVAC equipment, insulation, ductwork, windows, and building envelope to identify where energy is being wasted and where targeted improvements will make the biggest difference.",
    keywords: ["home energy audit Indian Trail NC", "HVAC energy audit Charlotte", "energy efficiency assessment NC", "home energy savings Charlotte"],
    signs: [
      "Energy bills are higher than you'd expect for your home size",
      "Some rooms are noticeably harder to heat or cool",
      "You feel drafts or temperature variations throughout the day",
      "Your HVAC system runs constantly but can't keep up",
      "You're planning HVAC upgrades and want to prioritize",
      "You want to qualify for energy efficiency rebates",
    ],
    included: [
      "Whole-home energy evaluation walkthrough",
      "HVAC system efficiency assessment",
      "Ductwork inspection for leaks and losses",
      "Insulation and building envelope review",
      "Utility bill analysis",
      "Prioritized improvement recommendations with ROI context",
    ],
    faq: [
      {
        q: "How long does a home energy audit take?",
        a: "A typical audit takes 1.5–3 hours depending on home size and complexity. We'll walk through the results with you before we leave.",
      },
      {
        q: "Can energy improvements qualify for tax credits or rebates?",
        a: "Yes. Many HVAC and insulation improvements qualify for federal tax credits and utility rebates. We'll point you toward available incentives.",
      },
    ],
    relatedServices: ["preventive-maintenance", "indoor-air-quality", "ac-installation"],
    metaTitle: "Home Energy Audits | Indian Trail, NC | Air Central Of The Carolinas",
    metaDescription: "Home energy audit services in Indian Trail, NC and Charlotte area. Identify energy waste, lower your bills, improve comfort. Call Air Central at (704) 288-4822.",
  },
  {
    slug: "commercial-hvac",
    title: "Commercial HVAC",
    shortTitle: "Commercial",
    icon: "Building2",
    category: "Commercial",
    description: "Commercial HVAC installation, repair, and maintenance for offices, retail spaces, and light industrial facilities.",
    longDescription: "Commercial HVAC systems require a different level of expertise — larger equipment, more complex controls, stricter code compliance, and higher stakes when something goes wrong. Air Central Of The Carolinas has the training, equipment, and experience to handle commercial projects across the Charlotte metro area, from small retail suites to multi-unit office buildings.",
    keywords: ["commercial HVAC Indian Trail NC", "commercial AC repair Charlotte", "commercial HVAC installation NC", "office HVAC Charlotte area"],
    signs: [
      "Your commercial space has uneven or unreliable temperature control",
      "HVAC-related comfort complaints from employees or customers",
      "Your equipment is aging and maintenance costs are rising",
      "You're building out a new commercial space",
      "Your system isn't meeting code or inspection requirements",
      "You need a reliable maintenance partner for your property",
    ],
    included: [
      "Commercial system inspection and needs assessment",
      "Equipment sizing and specification for new installations",
      "Rooftop unit (RTU) service and replacement",
      "Multi-zone system design and installation",
      "BAS/controls integration",
      "Scheduled preventive maintenance agreements",
      "Emergency response priority service",
    ],
    faq: [
      {
        q: "Do you service rooftop units?",
        a: "Yes. We install, repair, and maintain rooftop units (RTUs) for commercial properties across the Charlotte metro area.",
      },
      {
        q: "Do you offer commercial maintenance agreements?",
        a: "Yes. We offer customized preventive maintenance plans for commercial clients with multiple systems or critical uptime requirements.",
      },
      {
        q: "How quickly can you respond to a commercial HVAC emergency?",
        a: "We prioritize commercial clients with active maintenance agreements and work to respond as quickly as possible to any urgent situation.",
      },
    ],
    relatedServices: ["preventive-maintenance", "indoor-air-quality", "home-energy-audits"],
    metaTitle: "Commercial HVAC Services | Indian Trail, NC | Air Central",
    metaDescription: "Commercial HVAC installation, repair, and maintenance in Indian Trail, NC and Charlotte area. Offices, retail, light industrial. Call (704) 288-4822.",
  },
];

export const serviceAreas = [
  { name: "Indian Trail", state: "NC", primary: true, description: "Our home base — fast local service throughout Indian Trail and surrounding neighborhoods." },
  { name: "Charlotte", state: "NC", primary: true, description: "Full service coverage across Charlotte proper and surrounding communities." },
  { name: "Matthews", state: "NC", primary: false, description: "Complete HVAC services for Matthews residents and businesses." },
  { name: "Monroe", state: "NC", primary: false, description: "Serving Monroe and Union County with residential and commercial HVAC." },
  { name: "Mint Hill", state: "NC", primary: false, description: "Local HVAC service for Mint Hill and the southeast Charlotte area." },
  { name: "Stallings", state: "NC", primary: false, description: "Heating and cooling service in Stallings, NC and nearby communities." },
  { name: "Waxhaw", state: "NC", primary: false, description: "HVAC services for Waxhaw homeowners and businesses." },
  { name: "Weddington", state: "NC", primary: false, description: "Serving Weddington with quality residential HVAC." },
  { name: "Marvin", state: "NC", primary: false, description: "HVAC installation, repair, and maintenance in Marvin, NC." },
  { name: "Pineville", state: "NC", primary: false, description: "Serving Pineville and the southwest Charlotte corridor." },
  { name: "Concord", state: "NC", primary: false, description: "HVAC services extending into Concord and Cabarrus County." },
  { name: "Fort Mill", state: "SC", primary: false, description: "Serving Fort Mill and York County, SC with licensed HVAC service." },
];

export const testimonials = [
  {
    name: "Jennifer M.",
    location: "Indian Trail, NC",
    service: "AC Repair",
    rating: 5,
    text: "Our AC went out on the hottest day of July. Air Central had someone at our door within a few hours, diagnosed the problem quickly, and had us back up and running by early afternoon. Professional, honest, and genuinely good people.",
  },
  {
    name: "David R.",
    location: "Matthews, NC",
    service: "AC Installation",
    rating: 5,
    text: "We replaced our 18-year-old system this spring. The team walked us through every option, helped us pick the right size and efficiency rating, and the installation was clean and complete. Already seeing the difference in our energy bills.",
  },
  {
    name: "Susan & Tom K.",
    location: "Charlotte, NC",
    service: "Preventive Maintenance",
    rating: 5,
    text: "We've been on their maintenance plan for two years now. Two visits a year, they always find small things before they become big problems, and the technicians are consistently thorough and respectful of our home.",
  },
  {
    name: "Marcus L.",
    location: "Waxhaw, NC",
    service: "Heating Repair",
    rating: 5,
    text: "Furnace stopped working the night before Thanksgiving. They came out the next morning, found a cracked heat exchanger — a safety issue they took seriously — and helped us make a smart decision about repair versus replacement. No pressure, just honest advice.",
  },
  {
    name: "Amanda F.",
    location: "Mint Hill, NC",
    service: "Heat Pump Installation",
    rating: 5,
    text: "Switched from a gas furnace to a heat pump system this fall. Air Central did the full evaluation, explained the pros and cons clearly, and the installation crew was excellent. Our heating bills are already noticeably lower.",
  },
  {
    name: "Robert P.",
    location: "Indian Trail, NC",
    service: "Commercial HVAC",
    rating: 5,
    text: "We manage three commercial properties in the area. Air Central handles all of them now. Responsive, reliable, and they treat our tenants' comfort like their own business depends on it — because apparently it does.",
  },
];

export const faq = [
  {
    question: "Do you offer emergency HVAC service?",
    answer: "Yes. We provide emergency service for heating and cooling failures. Call us at (704) 288-4822 any time and we'll get someone out to you as quickly as possible.",
  },
  {
    question: "Do you provide financing?",
    answer: "Yes. We offer flexible financing options to help make major system replacements or repairs more manageable. Ask about current terms and promotions when you call.",
  },
  {
    question: "What HVAC brands do you service?",
    answer: "We service and install all major brands including Carrier, Lennox, Trane, Goodman, Rheem, York, Bryant, and many others. Our technicians are trained on both residential and light commercial equipment.",
  },
  {
    question: "Do you work on commercial HVAC systems?",
    answer: "Yes. We service offices, retail spaces, and light industrial facilities throughout the Charlotte metro area. We offer both on-call commercial service and scheduled maintenance agreements.",
  },
  {
    question: "How often should my HVAC system be serviced?",
    answer: "We recommend twice per year — spring for your cooling system before the summer heat, and fall for your heating system before winter. At minimum, annual service keeps your warranty valid and your system running efficiently.",
  },
  {
    question: "What areas do you serve?",
    answer: "We primarily serve Indian Trail, Charlotte, Matthews, Monroe, Mint Hill, Stallings, Waxhaw, Weddington, Marvin, Pineville, Concord, and Fort Mill, SC. Not sure if you're in our area? Just call us.",
  },
  {
    question: "Do you offer free estimates?",
    answer: "We offer free estimates on new equipment installations and replacements. Diagnostic fees may apply for repair service calls, which are applied toward the repair cost.",
  },
];

export const specials = [
  {
    id: "spring-tune-up",
    title: "Spring AC Tune-Up",
    subtitle: "Limited Time Offer",
    description: "Get your cooling system ready for summer with a comprehensive 20-point AC tune-up. Clean coils, test refrigerant, inspect controls, and more.",
    offer: "$89",
    originalPrice: "$129",
    badge: "Most Popular",
    expires: "While supplies last",
    cta: "Book Tune-Up",
  },
  {
    id: "new-system-discount",
    title: "$500 Off New System Installation",
    subtitle: "Replacement Savings",
    description: "Save $500 on any complete system replacement — new AC, heat pump, or furnace installation. Includes free load calculation and written estimate.",
    offer: "$500 Off",
    originalPrice: null,
    badge: "Hot Deal",
    expires: "Limited time",
    cta: "Get Free Estimate",
  },
  {
    id: "maintenance-plan",
    title: "Annual Maintenance Plan",
    subtitle: "Year-Round Protection",
    description: "Two tune-up visits per year, priority service scheduling, 10% discount on all repairs, and no diagnostic fees.",
    offer: "$179/yr",
    originalPrice: "$258/yr",
    badge: "Best Value",
    expires: "Ongoing enrollment",
    cta: "Enroll Now",
  },
  {
    id: "manufacturer-rebate",
    title: "Manufacturer Rebates Available",
    subtitle: "On Select Equipment",
    description: "Ask about current manufacturer rebates on select high-efficiency systems. Savings up to $1,500 on qualifying equipment.",
    offer: "Up to $1,500",
    originalPrice: null,
    badge: "Check Availability",
    expires: "Rebates vary by product",
    cta: "Ask About Rebates",
  },
];

export const processSteps = [
  {
    number: "01",
    title: "Reach Out",
    description: "Call us or submit a request online. We'll confirm availability, gather basic information, and get you scheduled — no long hold times or runaround.",
  },
  {
    number: "02",
    title: "Evaluate Your System",
    description: "Our technician arrives on time, performs a thorough inspection, and gives you a clear picture of what's happening with your system.",
  },
  {
    number: "03",
    title: "Recommend the Right Solution",
    description: "We give you honest recommendations — not upsells. If a repair makes sense, we'll say so. If replacement is the smarter choice, we'll explain why.",
  },
  {
    number: "04",
    title: "Complete the Work Properly",
    description: "We do the job right the first time. Clean worksite, proper materials, code-compliant installation, and attention to the details that matter.",
  },
  {
    number: "05",
    title: "Restore Your Comfort",
    description: "Before we leave, we test everything, walk you through the work, and make sure you're fully satisfied. We don't consider the job done until you do.",
  },
];

export const whyUsPoints = [
  {
    icon: "ShieldCheck",
    title: "Honest, No-Pressure Recommendations",
    description: "We tell you what your system actually needs — not what generates the highest ticket. Our reputation is built on straight talk.",
  },
  {
    icon: "Wrench",
    title: "Dependable Workmanship",
    description: "We do the job right the first time. Clean installs, proper sizing, quality parts, and attention to code compliance.",
  },
  {
    icon: "MapPin",
    title: "Local Experience, Local Commitment",
    description: "We're based in Indian Trail. We know the climate, the housing stock, and the families and businesses we serve.",
  },
  {
    icon: "Zap",
    title: "Efficiency-Minded Solutions",
    description: "We consider your energy costs alongside comfort goals. The right system at the right efficiency level pays for itself over time.",
  },
  {
    icon: "Clock",
    title: "Responsive Service",
    description: "We show up when we say we will. Emergencies get priority. You won't be left waiting when your comfort is on the line.",
  },
  {
    icon: "Building2",
    title: "Residential & Commercial Capability",
    description: "From single-family homes to multi-unit commercial buildings, we have the training and equipment to handle the full scope.",
  },
];
